version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: aid-backend
    volumes:
      - /data/aid:/data
    environment:
      - FS_ROOT_PATH=/data # путь к данным на хосте не берётся из переменной окружения
    networks:
      - proxy
    restart: unless-stopped
    user: "1013:1013"

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_COPYRIGHT=${VITE_COPYRIGHT} # авторство устанавливается переменной окружения
    container_name: aid-frontend
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
