version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: aid-backend
    volumes:
      - /data/aid:/data
    environment:
      - PORT=3000
      - FS_ROOT_PATH=/data # путь к данным на хосте не берётся из переменной окружения
    networks:
      - proxy
    restart: unless-stopped
    user: "1013:1013"

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - VITE_COPYRIGHT=${VITE_COPYRIGHT} # авторство устанавливается переменной окружения
    container_name: aid-frontend
    networks:
      - proxy
    restart: unless-stopped

  runner-demo:
    build:
      context: runner/node
      dockerfile: Dockerfile
    container_name: aid-runner-demo
    environment:
      - PORT=3003
      - CALLBACK_BASE_URL=http://aid-backend:3000
    networks:
      - proxy
    restart: unless-stopped

  runner-crud-api-exporter:
    build:
      context: runner/crud-api-exporter
      dockerfile: Dockerfile
    container_name: aid-runner-crud-api-exporter
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
