import { promises as fs } from 'node:fs';
import { fileURLToPath } from 'node:url';

import type { FrozenContract } from '../contractFreeze.js';
import { entityKebab } from '../entitySlice.js';
import { callLLM } from '../llmClient.js';
import { parseLlmFiles } from './fileParser.js';
import type { FileEntry, StageResult } from './types.js';

const BACKEND_RULES_PATH = fileURLToPath(
  new URL('../../../context/prompts/backend-rules.md', import.meta.url),
);
const FRONTEND_RULES_PATH = fileURLToPath(
  new URL('../../../context/prompts/frontend-rules.md', import.meta.url),
);

/** Files this stage is allowed to write. Anything else from the LLM is dropped. */
const ALLOWED_PATHS = new Set([
  'server/src/app.module.ts',
  'client/src/App.tsx',
  'client/src/dataProvider.ts',
]);

interface EntityWiring {
  name: string;
  kebab: string;
  /** Imported NestJS module class name, e.g. `EquipmentTypesModule`. */
  moduleClass: string;
  /** Path used by `app.module.ts` import (no extension). */
  modulePath: string;
  /** Resource folder used by `App.tsx` imports (no extension). */
  resourcePath: string;
  /** React Admin resource name (URL slug and dataProvider key). */
  resourceName: string;
  /** Component basenames exported from the resource folder. */
  components: { list: string; create: string; edit: string; show: string };
}

/**
 * Phase 10 — integration stage. Wires per-entity Nest modules and React Admin
 * resources (produced by Phase 9) into the app shells via:
 *
 *   - server/src/app.module.ts
 *   - client/src/App.tsx
 *   - client/src/dataProvider.ts
 *
 * The LLM is told which entities exist and what import paths to use so it does
 * not have to invent them. Anything outside `ALLOWED_PATHS` is dropped.
 */
export async function runIntegrationStage(contract: FrozenContract): Promise<StageResult> {
  const backendRules = await fs.readFile(BACKEND_RULES_PATH, 'utf8');
  const frontendRules = await fs.readFile(FRONTEND_RULES_PATH, 'utf8');

  const wirings = contract.entities.map((e) => buildEntityWiring(e.name));

  const systemPrompt = [
    '# Integration Stage System Prompt',
    '',
    'You are wiring per-entity NestJS modules and React Admin resources into the',
    'app shells. Follow the relevant sections of the backend and frontend rules',
    'documents below. Only the three target files listed in the user prompt are',
    'in scope — anything else will be dropped.',
    '',
    '## backend-rules.md',
    '',
    backendRules,
    '',
    '## frontend-rules.md',
    '',
    frontendRules,
  ].join('\n');

  const userPrompt = buildIntegrationUserPrompt(wirings);

  const { content } = await callLLM({
    systemPrompt,
    userPrompt,
    maxTokens: 8000,
    temperature: 0.2,
    label: 'integration',
  });

  const parsed = parseLlmFiles(content);
  const kept: FileEntry[] = [];
  for (const f of parsed) {
    if (ALLOWED_PATHS.has(f.path)) {
      kept.push(f);
    } else {
      console.warn(
        `[integration] WARN dropped out-of-zone file "${f.path}" (allowed: ${[...ALLOWED_PATHS].join(', ')})`,
      );
    }
  }

  if (kept.length === 0) {
    throw new Error(`integration stage: no in-zone files returned (raw count=${parsed.length})`);
  }

  const got = new Set(kept.map((f) => f.path));
  for (const expected of ALLOWED_PATHS) {
    if (!got.has(expected)) {
      console.warn(`[integration] WARN expected file "${expected}" was not generated`);
    }
  }

  return { files: kept };
}

function buildEntityWiring(entityName: string): EntityWiring {
  const kebab = entityKebab(entityName);
  // Module class name = PascalCase of kebab + "Module", e.g. equipment-types -> EquipmentTypesModule
  const pascalKebab = kebab
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
  return {
    name: entityName,
    kebab,
    moduleClass: `${pascalKebab}Module`,
    modulePath: `./modules/${kebab}/${kebab}.module`,
    resourcePath: `./resources/${kebab}/${entityName}List`,
    resourceName: kebab,
    components: {
      list: `${entityName}List`,
      create: `${entityName}Create`,
      edit: `${entityName}Edit`,
      show: `${entityName}Show`,
    },
  };
}

function buildIntegrationUserPrompt(wirings: EntityWiring[]): string {
  return [
    'Generate the three integration files that wire all per-entity modules and',
    'React Admin resources into the app shells. The per-entity files have already',
    'been generated by previous stages — your job is purely to wire them.',
    '',
    '## Target files (only these are in scope)',
    '',
    '- `server/src/app.module.ts` — NestJS root module. Must import `ConfigModule.forRoot({ isGlobal: true })`,',
    '  the auth module from `./auth/auth.module`, and every entity module listed below.',
    '- `client/src/App.tsx` — React Admin `<Admin>` shell. Must import the `dataProvider` from',
    '  `./dataProvider`, the `authProvider` from `./auth/authProvider`, and register a `<Resource>`',
    '  for every entity listed below with `list`, `create`, `edit`, and `show` set.',
    '- `client/src/dataProvider.ts` — wraps `ra-data-simple-rest` against `import.meta.env.VITE_API_URL`,',
    '  parses the `Content-Range` header for pagination per `frontend-rules.md`, and serializes repeated',
    '  query params for array filters. Must attach the bearer token from `localStorage` (`kc_token`) on',
    '  every request via a custom `httpClient`.',
    '',
    '## Entity wiring inputs',
    '',
    'For each entity, use these exact import paths and identifiers — do not invent your own.',
    '',
    '```json',
    JSON.stringify(wirings, null, 2),
    '```',
    '',
    '## Resource component imports (frontend)',
    '',
    'For each entity `<Name>` with kebab `<kebab>`, import the four components from the resource folder:',
    '',
    '```ts',
    "import { <Name>List } from './resources/<kebab>/<Name>List';",
    "import { <Name>Create } from './resources/<kebab>/<Name>Create';",
    "import { <Name>Edit } from './resources/<kebab>/<Name>Edit';",
    "import { <Name>Show } from './resources/<kebab>/<Name>Show';",
    '```',
    '',
    'Use named imports — the resource files use named exports.',
    '',
    '## Strict response format',
    '',
    'Respond with a single JSON object only, no prose:',
    '',
    '```json',
    '{"files":[{"path":"server/src/app.module.ts","content":"..."},{"path":"client/src/App.tsx","content":"..."},{"path":"client/src/dataProvider.ts","content":"..."}]}',
    '```',
    '',
    'All file paths MUST exactly match one of the three target paths above. Do NOT generate any other',
    'file — entity modules, resource components, auth files, and Prisma schema are owned by other',
    'stages and will be dropped.',
  ].join('\n');
}
